suda-in/config/routes.rb
Sudain::Application.routes.draw do

  get "comments/index"

  get "comment/index"

  match 'user/edit' => 'users#edit', :as => :edit

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  
  match 'sessions' => 'sessions#create'
  
  match 'users' => 'users#create'
  
  match 'sudas' => 'sudas#create'
  
  match 'comments' => 'comments#create'

  match 'following' => 'home#following'  
  
  match 'followers' => 'home#followers' 
  
  match 'people' => 'home#people', :as => :people
  
  match 'search' => 'home#search', :as => :search
  
  match 'settings' => 'settings#index', :as => :settings
  
  match 'all' => 'home#all', :as => :all
  
  match '/settings/update_settings' => 'settings#update_settings', :as => :update_settings
  
  match 'videochat' => 'video_chat#index', :as => :video_chat
  
  match 'remove_friend/:username' => 'home#remove_friend'
  
  match '/more_suda/:page' => 'home#more_suda', :as => :more_suda
  
  match '/more_show_suda/:username/:page' => 'home#more_show_suda', :as => :more_show_suda
  
  match '/more_all_suda/:page' => 'home#more_all_suda', :as => :more_all_suda
  
  match '/more_search_suda/:page' => 'home#more_search_suda', :as => :more_search_suda
  
  match '/del_suda/:id' => 'home#del_suda', :as => :del_suda
  
  match 'rss' => 'home#rss', :as => :rss
  
  match 'rss/all' => 'home#all_rss', :as => :all_rss
  
  match 'rss/search/:q' => 'home#search_rss', :as => :search_rss
  
  match 'rss/:username' => 'home#user_rss', :as => :user_rss
  
  match 'twitter_callback' => 'sudas#twitter_callback', :as => :twitter_callback
  
  match ':username' => 'home#show', :as => :user_sudas
  
  match '/:username/toggle_follow' => 'home#toggle_follow', :as => :toggle_follow
  
  match '/:username/toggle_follow_via_ajax' => 'home#toggle_follow_via_ajax', :as => :toggle_follow_via_ajax
  
  resources :sessions

  resources :users
  
  resources :sudas

  root :to => "home#index"
  

end

suda-in/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

suda-in/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "#{APP_CONFIG['site_title']} Suda-in" %></title>
    <%= stylesheet_link_tag "application" %>
	<%= javascript_include_tag "jquery.js","jquery-ui.js","jrails.js","fix.js","application.js" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
	<meta name="viewport" content="width=device-width; initial-scale=0.56; maximum-scale=1.0; user-scalable=1;" />
	<script type="application/x-javascript">
		addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){
			window.scrollTo(0,1);
		}
	</script>
  </head>
  <body>
	<div id="header">
		<div id="logo">
			<%= link_to image_tag("logo.png", :alt => "#{APP_CONFIG['site_title']} Suda-in"), root_url %>
		</div>
		<div id="top_links_container2">
			<% if current_user %>
				<%= link_to "Settings", settings_path %> |
				<% unless APP_CONFIG['use_ldap'] %>
					<%= link_to "Edit", edit_path %> |
				<% end %>
				<%= link_to "Logout", logout_path %>
			<% else %>
				<%= link_to "Login", login_path %>
			<% end %>
		</div>
		<% if current_user %>
			<div id="top_links_container1">
				<%= link_to "Video Chat", video_chat_path %>
			</div>
		<% end %>
	</div>
	<div class="clear"></div>
    <div id="container">
		<table class="columns" cellspacing="0">
			<tbody>
				<tr>
					<td id="content_base" class="round-left column">
						<div id="main">
							<% flash.each do |name, msg| %>
								<%= content_tag :div, msg, :id => "flash_#{name}" %>
								<% end %>
							<%= content_tag :h1, yield(:title) if show_title? %>
							<%= yield %>
						</div>
					</td>
					<% if current_user && controller_name != "settings" %>
						<td id="side_base" class="round-right column">
							<div id="side">
								<%= render :partial => "/includes/side_contents" %>
							</div>
						</td>
					<% else %>
						<td id="side_base" class="round-right column">
							<div id="side">
								<%= render :partial => "/includes/side_settings" %>
							</div>
						</td>
					<% end %>
				</tr>
			</tbody>
		</table>
		<div id="footer" class="round">
			<h3 class="offscreen">Footer</h3>
			<ul class="footer-nav">
				<li class="first">© 2010 Suda-in</li>
			</ul>
		</div>
    </div>
  </body>
</html>