suda-in/config/routes.rb
Sudain::Application.routes.draw do

  get "comments/index"

  get "comment/index"

  match 'user/edit' => 'users#edit', :as => :edit

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  
  match 'sessions' => 'sessions#create'
  
  match 'users' => 'users#create'
  
  match 'sudas' => 'sudas#create'
  
  match 'comments' => 'comments#create'

  match 'following' => 'home#following'  
  
  match 'followers' => 'home#followers' 
  
  match 'people' => 'home#people', :as => :people
  
  match 'search' => 'home#search', :as => :search
  
  match 'settings' => 'settings#index', :as => :settings
  
  match 'all' => 'home#all', :as => :all
  
  match '/settings/update_settings' => 'settings#update_settings', :as => :update_settings
  
  match 'videochat' => 'video_chat#index', :as => :video_chat
  
  match 'remove_friend/:username' => 'home#remove_friend'
  
  match '/more_suda/:page' => 'home#more_suda', :as => :more_suda
  
  match '/more_show_suda/:username/:page' => 'home#more_show_suda', :as => :more_show_suda
  
  match '/more_all_suda/:page' => 'home#more_all_suda', :as => :more_all_suda
  
  match '/more_search_suda/:page' => 'home#more_search_suda', :as => :more_search_suda
  
  match '/del_suda/:id' => 'home#del_suda', :as => :del_suda
  
  match 'rss' => 'home#rss', :as => :rss
  
  match 'rss/all' => 'home#all_rss', :as => :all_rss
  
  match 'rss/search/:q' => 'home#search_rss', :as => :search_rss
  
  match 'rss/:username' => 'home#user_rss', :as => :user_rss
  
  match 'twitter_callback' => 'sudas#twitter_callback', :as => :twitter_callback
  
  match ':username' => 'home#show', :as => :user_sudas
  
  match '/:username/toggle_follow' => 'home#toggle_follow', :as => :toggle_follow
  
  match '/:username/toggle_follow_via_ajax' => 'home#toggle_follow_via_ajax', :as => :toggle_follow_via_ajax
  
  resources :sessions

  resources :users
  
  resources :sudas

  root :to => "home#index"
  

end

suda-in/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :login_required
  
  def index
    @sudas = current_user.our_sudas(1)
    @last_suda = current_user.sudas.last
    
    if params[:in_reply_to]
      @suda_value = "@#{params[:in_reply_to]} "
    elsif params[:in_resuda_of]
      suda_id = params[:in_resuda_of]
      suda = Suda.find_by_id(suda_id)
      user = User.find_by_id(suda.user_id)
      @suda_value = "RS @#{user.username}: #{suda.message}"
    else
      @suda_value = ''
    end
  end
  
  def rss
    @sudas = current_user.our_sudas(1)
    render :layout => false
    response.headers["Content-Type"] = "application/xml; charset=utf-8"
  end
  
  def all
    @sudas = Suda.all_sudas(1)
    @last_suda = current_user.sudas.last
    render :template => "/home/index", :locals => { :sudas => @sudas }
  end
  
  def all_rss
    @sudas = Suda.all_sudas(1)
    render :layout => false
    response.headers["Content-Type"] = "application/xml; charset=utf-8"
  end
  
  def show
    @user = User.find_by_username(params[:username])
    if @user
      @sudas = @user.my_sudas(1)
    else
      render :text => "<h3>There is no <font color='red'>#{params[:username]}</font></h3>"
    end
  end
  
  def user_rss
    @user = User.find_by_username(params[:username])
    if @user
      @sudas = @user.my_sudas(1)
    end
    render :layout => false
    response.headers["Content-Type"] = "application/xml; charset=utf-8"
  end
   
  def toggle_follow
    @user = User.find_by_username(params[:username])
    if current_user.is_friend? @user
      flash[:notice] = "You are no longer following @#{@user.username}"
      current_user.remove_friend(@user)
    else
      flash[:notice] = "You are now following @#{@user.username}"
      current_user.add_friend(@user)
    end
    redirect_to user_sudas_path(@user.username)
  end

  def toggle_follow_via_ajax
    user = User.find_by_username(params[:username])
    if current_user.is_friend? user
      current_user.remove_friend(user)
    else
      current_user.add_friend(user)
    end
    render :text => user.id
  end  
  
  def more_suda
    @sudas = current_user.our_sudas(params[:page])
    render :partial => "/includes/sudas_list", :locals => { :sudas => @sudas }
  end
  
  def more_all_suda
    @sudas = Suda.all_sudas(params[:page])
    render :partial => "/includes/sudas_list", :locals => { :sudas => @sudas }
  end
  
  def more_show_suda
    @user = User.find_by_username(params[:username])
    if @user
      @sudas = @user.my_sudas(params[:page])
    end
    render :partial => "/includes/sudas_list", :locals => { :sudas => @sudas }
  end
  
  def more_search_suda
    @q = params[:q]
    @page = params[:page]
    unless @page
      @page = 0
    end
    @sudas = Suda.find_by_search_query(@q, @page)
    render :partial => "/includes/sudas_list", :locals => { :sudas => @sudas }
  end
  
  def del_suda
    suda_id = params[:id]
    suda = Suda.find_by_id(suda_id)
    if suda.user_id != current_user.id
      result = {'code'=>'error','msg'=>"You can not delete other's suda."}
    elsif suda.created_at < 1.days.ago.to_date
      result = {'code'=>'error','msg'=>"You can not delete suda after 1 day."}
    else 
      suda.destroy
      result = {'code'=>'success','id'=>suda_id}
    end
    render :text => ActiveSupport::JSON.encode(result)
  end
  
  def following
    @friends = current_user.friends
  end
  
  def followers
    @friends = current_user.friends_of
  end
  
  def people
    if params[:person]
      @people = User.find(:all, :conditions=>["username like ? or nickname like ?", "%#{params[:person]}%", "%#{params[:person]}%"], :order => "created_at desc")
    else
      @people = User.all.sort_by{rand}.delete_if {|u| u.sudas.last==nil } 
    end
  end
  
  def remove_friend
    friend = User.find_by_username(params[:username])
    if friend
      current_user.remove_friend(friend)
      render :text => friend.id
    else
      render :text => friend.id
    end
  end
  
  def search 
    @q = params[:q]
    @page = params[:page]
    unless @page
      @page = 0
    end
    @sudas = Suda.find_by_search_query(@q, @page)
    render :template => '/home/index', :locals => { :sudas => @sudas }
  end
  
  def search_rss
    @q = params[:q]
    @page = params[:page]
    unless @page
      @page = 0
    end
    @sudas = Suda.find_by_search_query(@q, @page)
    render :layout => false
    response.headers["Content-Type"] = "application/xml; charset=utf-8"
  end
end

suda-in/app/helpers/home_helper.rb
module HomeHelper
  def link_user(txt)
  	if match = txt.match(/.*?(@)((?:[a-z0-9][a-z0-9]+))(:|\s)/i)
      user = match[2]
      if user
        txt.gsub!(user, "<a href='#{request.env["SERVER_ADDR"]}/#{user}'>#{user}</a>")
      end
    end
  	txt
  end
  
  def link_url(txt)
    auto_link(txt, :html => { :target => '_blank' }) do |text|
      truncate(text, :length => 15)
    end
  end
end

suda-in/app/views/home/followers.html.erb
<%= render :partial => "/includes/people_list", :locals => { :people => @friends } %>

suda-in/app/views/home/following.html.erb
<%= render :partial => "/includes/people_list", :locals => { :people => @friends } %>

suda-in/app/views/home/index.html.erb
<% 
	if controller.action_name == 'search'
		href = "/rss/search/#{@q}"
	elsif controller.action_name == 'all'
		href = "/rss/all"
	else
		href = "/rss"
	end
%>
<!-- <link rel="alternate" type="application/rss+xml" title="RSS" href="<%=href%>" /> -->

<%- form_for Suda.new do |s| -%>
	<div id="new_suda_form">
		<h3 id="status_label" style="float:left;">What's happening?</h3>
		<h3 id="char_count">140</h3>
		<%= s.text_area :message, :value => @suda_value  %>
		<% if @suda_value %><script>detect_message();</script><% end %>
		<% if @last_suda %>
			<div id="latest_message">
				<strong>Last: </strong><%= h @last_suda.message %>
				<span class="post_ago"><%= distance_of_time_in_words_to_now(@last_suda.created_at) %> ago</span>
			</div>
		<% end %>
		
		<div id="submit_button_container">
			<span id="check_twit"><%= check_box_tag 'twit', 'yes' %>also send to twitter</span>
			<%= s.submit "Update", :id=>"update_button", :class => "button button-disabled", :disabled =>"disabled" %>
		</div>
		<div class="clear"></div>
	</div>
<%- end -%>

<% if controller.action_name == "search" %>
	<div id="search_result">
		<h1 id="heading">
			<% if @sudas.count > 0 %>
				Real-time search results for <b><%=@q%></b>
			<% else %>
				No real-time search results for <b><%=@q%></b>
			<% end %>
			<span class="name-search-link"><%= link_to "Search for users »", people_path(:person=>@q) %></li>
		</h1>
	</div>
<% end %>

<% if controller.action_name == "all"%>
	<h3><%=APP_CONFIG['site_title']%> all sudas</h3>
<% end %>
<%= render :partial => "/includes/sudas_list", :locals => { :sudas => @sudas }%>


	<div id="pagination">
		<% if controller.action_name=='all' %>
			<% more_action = "more_all_suda()" %>
		<% elsif controller.action_name=='search' %>
			<% more_action = "more_search_suda('#{CGI::escape(@q)}')" %>
		<% else %>
			<% more_action = "more_suda()" %>
		<% end %>
		<%= link_to_function "More", more_action, :class => 'more' %>
	</div>

suda-in/app/views/home/people.html.erb
<h2>People in <%=APP_CONFIG['site_title']%></h2>
<%= render :partial => "/includes/people_list", :locals => { :people => @people } %>

suda-in/app/views/home/show.html.erb
<!-- <link rel="alternate" type="application/rss+xml" title="RSS" href="/rss/<%=@user.username%>" /> -->

<h1>
<%= image_tag "/emblems/#{@user.picture}", :onerror => "this.src='#{@user.gravatar_url(:size=>73)}'", :title => @user.nickname, :width=>73, :height=>73 %>
<%= @user.username %>
</h1>

<div class="profile-controls round">
	<% if current_user.username == @user.username %>
		<strong>That's you!</strong>
	<% else %>
		<%- form_tag toggle_follow_path do -%>
			<% if current_user.is_friend? @user %>
				<%= submit_tag "You are Following!", :class => "button" %>
			<% else %>
				<%= submit_tag "Follow", :class => "button" %>
			<% end %>
		<%- end -%>
	<% end %>
</div>

&nbsp;


<%= render :partial => "/includes/sudas_list", :locals => { :sudas => @sudas }%>

<div id="pagination">
		<%= link_to_function "More", "more_show_suda('#{@user.username}')", :class => 'more' %>
</div>