suda-in/config/routes.rb
Sudain::Application.routes.draw do

  get "comments/index"

  get "comment/index"

  match 'user/edit' => 'users#edit', :as => :edit

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  
  match 'sessions' => 'sessions#create'
  
  match 'users' => 'users#create'
  
  match 'sudas' => 'sudas#create'
  
  match 'comments' => 'comments#create'

  match 'following' => 'home#following'  
  
  match 'followers' => 'home#followers' 
  
  match 'people' => 'home#people', :as => :people
  
  match 'search' => 'home#search', :as => :search
  
  match 'settings' => 'settings#index', :as => :settings
  
  match 'all' => 'home#all', :as => :all
  
  match '/settings/update_settings' => 'settings#update_settings', :as => :update_settings
  
  match 'videochat' => 'video_chat#index', :as => :video_chat
  
  match 'remove_friend/:username' => 'home#remove_friend'
  
  match '/more_suda/:page' => 'home#more_suda', :as => :more_suda
  
  match '/more_show_suda/:username/:page' => 'home#more_show_suda', :as => :more_show_suda
  
  match '/more_all_suda/:page' => 'home#more_all_suda', :as => :more_all_suda
  
  match '/more_search_suda/:page' => 'home#more_search_suda', :as => :more_search_suda
  
  match '/del_suda/:id' => 'home#del_suda', :as => :del_suda
  
  match 'rss' => 'home#rss', :as => :rss
  
  match 'rss/all' => 'home#all_rss', :as => :all_rss
  
  match 'rss/search/:q' => 'home#search_rss', :as => :search_rss
  
  match 'rss/:username' => 'home#user_rss', :as => :user_rss
  
  match 'twitter_callback' => 'sudas#twitter_callback', :as => :twitter_callback
  
  match ':username' => 'home#show', :as => :user_sudas
  
  match '/:username/toggle_follow' => 'home#toggle_follow', :as => :toggle_follow
  
  match '/:username/toggle_follow_via_ajax' => 'home#toggle_follow_via_ajax', :as => :toggle_follow_via_ajax
  
  resources :sessions

  resources :users
  
  resources :sudas

  root :to => "home#index"
  

end

suda-in/app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  @@directory = "#{RAILS_ROOT}/public/emblems"
  
  def upload_profile_image(user)
    unless user['profile_image_uploaded_data']
      return false
    end
    extension = File.extname(user['profile_image_uploaded_data'].original_filename)
    extension = extension.downcase
    unless extension=='.jpg' || extension=='.png' || extension=='.gif'
      flash[:error] = "Only jpg,png,gif file can be used for profile picture."
      return false
    end
    helper = Object.new.extend(ActionView::Helpers::NumberHelper)
    filesize = user['profile_image_uploaded_data'].size
    if filesize > 1024 * 1000 * 5
      flash[:error] = "(#{helper.number_to_human_size(filesize)}) File size should be less than 5 KB."
      return false
    end
    filename = current_user.username
    name = filename + extension
    # create the file path
    path = File.join(@@directory, name)
    # write the file
    File.open(path, "wb") { |f| f.write(user['profile_image_uploaded_data'].read) }
    User.find_by_id(current_user.id).update_attribute(:picture, name)
  end
  
  def delete_profile_image(user)
    del_file = File.join(@@directory, current_user.username + ".jpg")
    File.delete(del_file) if File.exist?(del_file)
    del_file = File.join(@@directory, current_user.username + ".png")
    File.delete(del_file) if File.exist?(del_file)
    del_file = File.join(@@directory, current_user.username + ".gif")
    File.delete(del_file) if File.exist?(del_file)
    flash[:notice] = "Uploaded image was deleted. You are using Gravatar"
  end
  
  def update_settings
    if params[:del_emblem]=="y"
      self.delete_profile_image(params[:user])
    else
      self.upload_profile_image(params[:user])
    end
    redirect_to settings_path
  end

end

suda-in/app/helpers/settings_helper.rb
module SettingsHelper
end

suda-in/app/views/settings/index.html.erb
<div id="settings_container">
	<h2><%= link_to image_tag("/emblems/#{current_user.picture}", :width=>25, :height=>25, :border=>0, :align=>"top", :onerror => "this.src='#{current_user.gravatar_url}'"), user_sudas_path(current_user.username) %> <%=current_user.username%>'s settings</h2>
	
	<% form_tag (update_settings_path, :id => :settings_form, :multipart => true) do |u| %>
		<fieldset class="common-form standard-form">
			<table class="input-form" cellspacing="0">
				<tbody>
					<tr>
						<th>
							<label for="profile_image_uploaded_data">Picture</label>
						</th>
						<td class="avatar-settings avatar-exists">
							<%= image_tag "/emblems/#{current_user.picture}", :align => "top", :class=>"profile-image", :width => 73, :height => 73, :onerror => "this.src='#{current_user.gravatar_url(:size=>73)}'", :title => current_user.nickname %>
							<span class="avatar-upload">
								<%= file_field :user, :profile_image_uploaded_data, :size => 15 %>
								<p><small>Maximum size of 5k. JPG, GIF, PNG.</small>
							</span>
							<span class="avatar-options">
								<!--<%= link_to "Change Image", :class => "change-image" %>-->
								<%= link_to "Delete uploaded Image and Use Gravatar", update_settings_path(:del_emblem=>"y") %>
							</span>
							
						</td>
					</tr>
				</tbody>
			</table>
		</fieldset>
		<fieldset class="common-form standard-form">
			<table class="input-form" cellspacing="0">
				<tbody>
					<!-- <tr>
											<th>
												<label for="nick_name">Name</label>
											</th>
											<td>
												<%= text_field :user, :nickname %>
												<p><small>Enter your real name, so people you know can recognize you.</small>
											</td>
										</tr> -->
					<tr>
						<th></th>
						<td>
							<%= submit_tag "Save", :id=>"save_settings_button", :class => "button" %>
						</td>
					</tr>
				</tbody>
			</table>
		</fieldset>
	<% end %>
</div>