suda-in/config/routes.rb
Sudain::Application.routes.draw do

  get "comments/index"

  get "comment/index"

  match 'user/edit' => 'users#edit', :as => :edit

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  
  match 'sessions' => 'sessions#create'
  
  match 'users' => 'users#create'
  
  match 'sudas' => 'sudas#create'
  
  match 'comments' => 'comments#create'

  match 'following' => 'home#following'  
  
  match 'followers' => 'home#followers' 
  
  match 'people' => 'home#people', :as => :people
  
  match 'search' => 'home#search', :as => :search
  
  match 'settings' => 'settings#index', :as => :settings
  
  match 'all' => 'home#all', :as => :all
  
  match '/settings/update_settings' => 'settings#update_settings', :as => :update_settings
  
  match 'videochat' => 'video_chat#index', :as => :video_chat
  
  match 'remove_friend/:username' => 'home#remove_friend'
  
  match '/more_suda/:page' => 'home#more_suda', :as => :more_suda
  
  match '/more_show_suda/:username/:page' => 'home#more_show_suda', :as => :more_show_suda
  
  match '/more_all_suda/:page' => 'home#more_all_suda', :as => :more_all_suda
  
  match '/more_search_suda/:page' => 'home#more_search_suda', :as => :more_search_suda
  
  match '/del_suda/:id' => 'home#del_suda', :as => :del_suda
  
  match 'rss' => 'home#rss', :as => :rss
  
  match 'rss/all' => 'home#all_rss', :as => :all_rss
  
  match 'rss/search/:q' => 'home#search_rss', :as => :search_rss
  
  match 'rss/:username' => 'home#user_rss', :as => :user_rss
  
  match 'twitter_callback' => 'sudas#twitter_callback', :as => :twitter_callback
  
  match ':username' => 'home#show', :as => :user_sudas
  
  match '/:username/toggle_follow' => 'home#toggle_follow', :as => :toggle_follow
  
  match '/:username/toggle_follow_via_ajax' => 'home#toggle_follow_via_ajax', :as => :toggle_follow_via_ajax
  
  resources :sessions

  resources :users
  
  resources :sudas

  root :to => "home#index"
  

end

suda-in/app/views/includes/_comments_list.html.erb
		<% suda.comments.each do |comment| %>
		<li class="comments_li">
			<%= image_tag "/emblems/#{comment.user.picture}", :onerror => "this.src='#{comment.user.gravatar_url}'", :width => 30, :height => 30, :title => suda.user.nickname %>
			<div class="comment_message_container">
				<div class="comment_message">
					<span id="comment_user_id">comment.user.id</span>
					<span id="comment_message_id">comment.message </span>
				</div>
				<div class="time_ago">
					<%= distance_of_time_in_words_to_now(comment.created_at) %> ago
				</div>
			</div>
		</li>
		<div class="clear"></div>
		<% end %>

suda-in/app/views/includes/_people_list.html.erb
<% if params[:person] %>
	<div id="search_result">
		<h1 id="heading">
			<% if @people.count > 0 %>
				User search results for <b><%=params[:person]%></b>
			<% else %>
				No User search results for <b><%=params[:person]%></b>
			<% end %>
			<span class="name-search-link"><%= link_to "Search for real-time »", search_path(:q=>params[:person]) %></li>
		</h1>
	</div>
<% end %>

<ul id="sudas_list">
 	<% if people.count > 0 %>
		<% people.each do |person| %>
			<li class="sudas_li <% if people.first == person %> first<% end %>" id="<%= person.username%>">
				<!-- <%= image_tag person.gravatar_url %> -->
				<%= image_tag "/emblems/#{person.picture}", :onerror => "this.src='#{person.gravatar_url}'", :width => 50, :height => 50, :title => person.nickname %>
				<div class="suda_message_container">
					<span class="label screenname">
						<%= link_to person.username, user_sudas_path(person.username) %>
					</span>
					<br/>
					<span class="label nickname"> 
						<%= person.nickname%>
					</span>
					<div class="people_suda">
						<%= h person.sudas.last.message if person.sudas.last %>
					</div>
					<div class="post_ago">
						<%= "#{distance_of_time_in_words_to_now(person.sudas.last.created_at)} ago" if person.sudas.last %>
						<%= person.sudas.last.agent ? "via #{person.sudas.last.agent}" : '' if person.sudas.last %>
					</div>
				</div>
				<div class="button_container">
					<input type="button" class="button" name="<%= person.username%>" id="btn_follow_<%=person.id%>" value="<% if current_user.is_friend? person %>You are Following!<% else %>Follow<% end %>" onclick="toggle_follow_ajax('<%= person.username%>')" />
				</div>
				<div class="clear"></div>
			</li>
		<% end %>
	<% end %>
</ul>

suda-in/app/views/includes/_side_contents.html.erb
<div id="my_info_container">
	<%= link_to image_tag("/emblems/#{current_user.picture}", :onerror => "this.src='#{current_user.gravatar_url(:size=>30)}'", :border=>0, :width=>30, :height=>30, :title => current_user.nickname), user_sudas_path(current_user.username) %>
	<div class="contents">
		<%= link_to current_user.username, user_sudas_path(current_user.username) %><br/>
		<span class="small"><%= pluralize(current_user.sudas.length, "Suda") %></span>
	</div>
</div>
<div class="clear"></div>
<div id="side_content_container">
	<h4><%= link_to "#{current_user.friends.count} following", following_path  %></h4>
	<h4><%= link_to pluralize(current_user.friends_of.count, "follower"), followers_path %></h4>
</div>
<% form_tag (search_path, :method => :get) do %>
<div id="search_bar">
	<%= text_field_tag :q, @q, :class => "text"%>
	<!-- <div id="search_submit_button">&nbsp</div> -->
	<%= image_submit_tag("nav_search_submit.png", :id => 'search_submit_button') %>
	<!-- <%= submit_tag "search" %> -->
</div>
<% end %>
<div id="show_all">
	<h4><%= link_to "Show all sudas", all_path  %></h4>
	<h4><%= link_to "Show people", people_path  %></h4>
</div>
<% if current_user.friends_of.count > 0 %>
	<div>
		<h4>Following</h4>
		<% current_user.friends.each do |friend| %>
			<%= link_to image_tag("/emblems/#{friend.picture}", :width=>25, :height=>25, :onerror => "this.src='#{friend.gravatar_url(:size=>25)}'", :border => 0, :alt => friend.username, :title => friend.nickname), user_sudas_path(friend.username) %>
		<% end %>
	</div>
	<br />
<% end %>
<div id="rssfeed">
	<% if controller.action_name == 'search' %>
		<%= link_to "RSS Feed of search result for '#{@q}'", search_rss_path(@q), :class=>'rss' %>
	<% elsif controller.action_name == 'all' %>
		<%= link_to "RSS Feed of all sudas", all_rss_path, :class=>'rss' %>
	<% elsif controller.action_name == 'show' %>
		<%= link_to "RSS Feed of #{current_user.username}", user_rss_path(@user.username), :class=>'rss' %>
	<% elsif controller.action_name == 'index' %>
		<%= link_to "RSS Feed", rss_path, :class=>'rss' %>
	<% end %>
</div>

suda-in/app/views/includes/_side_settings.html.erb
<!-- <h3>Tips</h3>
<p>Filling in your profile information will help people find you on Suda-in.</p> -->

suda-in/app/views/includes/_sudas_list.html.erb
<ul id="sudas_list">
	<% @sudas.each do |suda| %>
		<li id="sudas_id_<%= suda.id %>" class="sudas_li<% if sudas.first == suda %> first<% end %>">
			<%= image_tag "/emblems/#{suda.user.picture}", :onerror => "this.src='#{suda.user.gravatar_url}'", :width => 50, :height => 50, :title => suda.user.nickname %>
			<div class="suda_message_container">
				<div class="suda_message">
					<span id="suda_user_id_<%= suda.id %>"><%= link_to suda.user.username, user_sudas_path(suda.user.username) %></span>
					<span id="suda_message_id_<%= suda.id %>"><%= auto_link_urls(link_user(link_url((h suda.message))),{:sanitize=>true},{}) %></span>
				</div>
				<div class="time_ago">
					<%= distance_of_time_in_words_to_now(suda.created_at) %> ago
					<%= suda.agent ? "via #{suda.agent}" : '' %>
				</div>
				<ul id="opt_ul_id_<%= suda.id %>" class="actions-hover <% if current_user.username == suda.user.username %>del_ul<% else %>re_ul<% end %>">
					<% if current_user.username == suda.user.username %>
						<li>
							<span class="del">
								<span class="delete-icon icon"></span>
								<%= link_to_function "Delete", "if (confirm('Sure you want to delete this suda? There is No undo!')) delsuda('"+suda.id.to_s+"');" %>
							</span>
						</li>
					<% else %>
						<li>
							<span class="reply">
								<span class="reply-icon icon"></span>
								<% if controller.action_name == 'show' %>
									<%= link_to "Reply", root_path(:in_reply_to => suda.user.username) %>
								<% else %>
									<%= link_to_function "Reply", "reply('"+suda.user.username+"');" %>
								<% end %>
							</span>
						</li>
						<li>
							<span class="resuda-link">
								<span class="resuda-icon icon"></span>
								<% if controller.action_name == 'show' %>
									<%= link_to "Resuda", root_path(:in_resuda_of => suda.id) %>
								<% else %>
									<%= link_to_function "Resuda", "resuda('"+suda.id.to_s+"');" %>
								<% end %>
							</span>
						</li>
					<% end %>
				</ul>
			</div>
			
			<% if APP_CONFIG['use_comment'] %>
				<%- form_for Comment.new do |c| -%>
				<div id="comments_id_<%= suda.id %>" class="comments_box">
					<div class="clear"></div>
					<ul id="comments_list">
						<div id="comments_list_body">
							<!-- 
							<%= render :partial => "/includes/comments_list", :locals => { :suda => suda }%>
							-->
						</div>
						<li id="comment_form_<%=suda.id%>" class="comment_form">
							<textarea id="comment_text_<%=suda.id%>" rows=2 cols=61></textarea>
						</li>
					</ul>
				</div>
				<%- end -%>
			<% end %>
			
			<div class="clear"></div>
		</li>
	<% end %>
</ul>